yu07na06/TheSurveyZone

- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/README.md
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/pages/CreateSurveyPage.js
1. 객관식 보기추가 기능 구현
2. 설문생성 페이지에서 필요한 컴포넌트들(객관식UI,객관식Comp / 주관식UI,주관식Comp / 선형배율UI, 선형배율Comp )파일 추가
> Feat_Front/Survey [type add: mutiple choice]

- front/src/components/login/UI/Login.js
- front/src/components/register/UI/Register.js
- front/src/index.js
1. index에 , 삭제
2. login/register에 import삭제
> Etc_Front [modify import]

- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
1. 객관식 보기 삭제 기능 추가
2. 날짜 선택 기능 수정
> Fix_Front/Survey [multi choice option delete, modify datepicker]

- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
> Feat_Front/Survey/request_object [add multipleChoice object]

- back/src/main/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplication.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/Answer.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/Select.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/Survey.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveyInsertDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/repository/SurveyRepository.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/application.properties
- back/src/test/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplicationTests.java
설문조사 삽입 API 추가 / SurveyDAO, SurveyService 추가
> Feat_Back/SurveyInsert

- front/package.json
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/lib/api/survey.js
1. 서버 전송 객체 타입 수정(객관식만 완성)
2. 서버 전송 기능 구현
> Feat_Front/Survey_submit [modify object, add axios survey]

- front/package.json
- front/src/components/login/comp/LoginComp.js
- front/src/components/register/comp/RegisterComp.js
- front/src/lib/api/auth.js
로그인/회원가입 서버 통신 기능 수정 및 완료
- 로그인 : 로그인 성공/실패 기능 완료
- 회원가입 : 이메일 중복 확인 및 회원가입 성공/실패 기능 완료
> Fix front/auth

- front/src/components/login/comp/LoginComp.js
1. 로그인 성공시  로컬스토리지에  res받은 값을 삽입
2. 회원가입시 api요청을 통해 db에 존재하는 데이터 인지 아닌지 여부에 따라 UI에 text 출력 구현
> Feat_Front/Login_out/localstorage

- front/src/App.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/ReadOnly.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/ReadOnlyComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/pages/ReadOnlyPage.js
1. 객관식 태그 추가
2. 주관식 selectList object 삽입
3. 선형배율 구성
4. 보기만 가능한 설문 페이지 생성
> Feat front/survey create

- back/src/main/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplication.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/QType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/AnswerInsertDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveyInsertDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/QuestionType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/SurveyProgressType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/SurveyType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Answer.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Select.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Survey_Mongo.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mysql/Survey_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/repository/SurveyRepository.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/application.properties
- back/src/main/resources/config/mybatis-config.xml
- back/src/main/resources/mappers/survey.xml
- back/src/test/java/com/mongoosereum/dou_survey_zone/DouSurveyMySQLZoneApplicationTests.java
설문조사 Form 생성 API MySQL + MongoDB 연결 완료
> Feat_Back/SurveyInsert_MySQL

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveyInsertDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveySelectDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/QuestionType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/SurveyProgressType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/SurveyType.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mysql/Survey_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/application.properties
API 및 Entity 전체적으로 리팩토링 및 보완
Null 값 수정 및 변수명, 함수명 수정
> Refactor_Back/SurveyAPI

- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
> Fix_Front/Survey_required [Add required to form]

- front/package.json
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/pages/SurveySubmitPage.js
- front/yarn.lock
1. 사용자 설문 UI 구현
2. 사용자 설문 API 구현
> Feat_Front/SubmitSurvey [Add mainSurvey]

- front/package.json
- front/src/components/Main.js
- front/yarn.lock
> Feat_Front/Main_chart [Add user chart]

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/ParticipationController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/Repository/PartRepository.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/ACC/ACC_Age.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/ACC/ACC_Gender.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/Part_Acc_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/service/PartService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dto/UserDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/repository/UserRepository.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/service/UserService.java
- back/src/main/resources/config/mybatis-config.xml
- back/src/main/resources/mappers/participation.xml
- back/src/main/resources/mappers/user.xml
jwt 코드 리펙토링
login 오류 fix
누적이용자수 구현
> fix jwt and acc user

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/InsertAnswerDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/InsertSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SelectSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Answer.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Select.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Survey_Mongo.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/application.properties
- back/src/main/resources/mappers/survey.xml
설문조사 API 수정 및 삭제 추가 & Survey API 리팩토링
> Feat_Back/SurveyDelete&Update

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/WebSecurityConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/MainPageController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/ACC/ACC_Age.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/ACC/ACC_Gender.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/entity/Part_Acc_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/security/JwtAuthenticationFilter.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
> Refactor_Back/MainPage

- front/package.json
- front/src/components/common/UI/Header.js
- front/src/components/login/comp/LoginComp.js
- front/src/components/register/comp/RegisterComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/index.js
- front/src/lib/api/auth.js
- front/yarn.lock
로그인 시 API 반환값으로 토큰을 받아 쿠키에 저장하여 로그인 상태를 관리
> Feat_Front/AuthCookie

- front/src/components/register/UI/Register.js
- front/src/components/register/comp/RegisterComp.js
> Feat_Front/Register_Email_Check

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/MainPageController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/mappers/survey.xml
내 설문 조사 API 추가, 설문조사 Create, Delete 수정
> Feat_Back/MySurvey 

- front/package.json
- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/common/UI/Header.js
- front/src/index.js
- front/src/lib/api/survey.js
- front/src/lib/createRequestSaga.js
- front/src/modules/chartReducer.js
- front/src/modules/index.js
- front/yarn.lock
메인 페이지 차트에 필요한 데이터를 리덕스 및 사가를 사용하여 동기적으로 처리하였다.
SAGA를 사용하지 않을시 유효한 데이터 참조가 불가능했기 때문..
> Feat front/main charts

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dto/UserDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/service/UserService.java
> Refactor_Back/CheckEmail

- front/src/components/register/UI/Register.js
- front/src/components/register/comp/RegisterComp.js
> Fix_Front/Register[checkEmail -req -api]

- front/package.json
- front/src/components/login/comp/LoginComp.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
> Feat_Front/Delete_Survey_QuestionList

- front/package.json
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
설문 응답 페이지 구현
- 객관식 미완성
- 선형배율 라디오 버튼 개수 미완성
> Feat_Front/Survey_submit [submit user survey]

- back/pom.xml
- back/src/main/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplication.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/WebSecurityConfig.java
- back/src/main/resources/META-INF/MANIFEST.MF
> Refactor_Back/Enum

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/InsertSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SelectSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/tag/dao/TagDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/tag/entity/SurveyTag.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/tag/entity/Tag.java
- back/src/main/resources/application.properties
- back/src/main/resources/config/mybatis-config.xml
- back/src/main/resources/mappers/tag.xml
Tag 관련 기능 추가
- Survey Insert시 Tag List 출력
- Survey Select시 해당 Survey의 Tag 출력
- 메인 페이지에서 필요한 게시물이 존재하는 Tag List 출력
> Feat_Back/SurveyTag

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/SwaggerConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/InsertAnswerDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/InsertSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SelectSurveyDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Answer.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Select.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Survey_Mongo.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mysql/Survey_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dto/UserDTO.java
> Fix_Back/Swagger

- back/pom.xml
- back/src/main/java/META-INF/MANIFEST.MF
- back/src/main/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplication.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/MySQLDBConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/SwaggerConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/config/WebSecurityConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mongo/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/service/UserService.java
- back/src/main/resources/application.properties
> Refactor_Back/ServerDeployment

- back/src/main/java/META-INF/MANIFEST.MF
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/MainPageController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/dto/ParticipationDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/participation/service/PartService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/entity/mysql/Survey_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/tag/dao/TagDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/user/service/UserService.java
- back/src/main/resources/mappers/user.xml
> login refector and searchID

- front/package.json
- front/src/components/Main.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
설문 응답 시,
- 객관식의 체크 박스 기능 추가
- 주관식 입력상자 추가
- 선형배율 라디오 단일 선택 기능 추가
> Feat_Front/SubmitSurvey_v2 [ADD checkbox & radio ]

- front/package.json
- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/BeforeSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/modules/chartReducer.js
- front/src/modules/index.js
- front/src/modules/submitReducer.js
1. 사전 설문 응답 페이지에서 성별 및 연령대 수집완료
2. 설문 응답 페이지 [선형배율] 시작값 및 끝값 가져오기
3. 약간의 UI 수정 [선형배율 - 라디오버튼]
> Feat_Front/SubmitSurvey_v2 [ADD beforeData | submitReducer]

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/lib/api/home.js
> Feat_Front/API response TagList

- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/common/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/dto/SurveyResultDTO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/v1/api/survey/service/SurveyService.java
- back/src/main/resources/application.properties
[SurveyResult]
- resultMap 존재하는 답변에 대한 key,value쌍만이 아닌 보기(선택지)에 대한 모든 key, value쌍 제공하도록 변경
[Swagger Response 변경]
> Fix_Back/SurveyResult

- front/package.json
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/lib/api/survey.js
> Feat_Front/createSurvey_tags [ADD tags]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailHandler.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/paging/PageCriteria.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/paging/PaginationInfo.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/Surveylist_MySQL.java
- back/src/main/resources/application.properties
- back/src/main/resources/config/mybatis-config.xml
- back/src/main/resources/mappers/participation.xml
- back/src/main/resources/mappers/survey.xml
- back/src/main/resources/mappers/tag.xml
- back/src/main/resources/mappers/user.xml
> Refect_Back/DB directory refectoring

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/lib/api/home.js
> Feat_Front/Main_paging [ADD paging]

- front/package.json
- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/modules/submitReducer.js
nananananana를 temptemp에 붙여서 front_develop에 올리기 위한 과정
> temp [last]

- front/package.json
- front/src/components/MainComp.js
- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/modules/submitReducer.js
> Feat_Front/SubmitSurvey_submit

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/participation/Participation.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertAnswerReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/SurveyListPageReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/config/WebSecurityConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/JwtAuthenticationFilter.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/TokenProvider.java
- back/src/main/resources/config/mybatis-config.xml
- back/src/main/resources/mappers/participation.xml
InsertAnswer [설문 제출]시 참여자 정보 insert 되도록 수정
> Back_Fix/InsertAnswer

- back/pom.xml
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/config/AmazonS3Config.java
- back/src/main/resources/application.properties
- back/src/main/resources/mappers/participation.xml
> Feat_Back/temp

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
설문조사 API 수정 삭제 결과-조회 Security  인증 후 가능하도록 변경
> Fix_Back/Survey_Authentication

- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/lib/api/survey.js
1. 내설문 페이지에서 URL복사 기능 수정
[기존 사용하던 클립보드(네비게이터)는 https에서만 지원하여 클립보드함수 구현]
2. 내설문 페이지 설문 삭제 기능 구현
> Fix_Front/url_copy&mySurveyDelete

- front/package.json
- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/comp/BeforeSurveyComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
설문 생성 페이지에서 설문 삭제 시, 오류 수정
[설문 생성 후 제출 시, API request parameter 수정]
> Fix_Front/CreateSurvey_delete [ modify delete error ]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/user/User.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/user/UserService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/SearchPWReq.java
- back/src/main/resources/mappers/user.xml
- back/src/main/resources/templates/resetPW.html
> Feat_Back/User_SearchPW API

- front/src/App.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/pages/UpdatePage.js
> Feat_Front/UpdateSurvey_v1 [ADD UpdateSurvey]

- back/pom.xml
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/participation/ParticipationService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/SurveyPartCheckRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/config/RedisDBConfig.java
- back/src/main/resources/mappers/participation.xml
> Feat_back/checksurveypart

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/SurveyDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/SurveyDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/AuthenticationException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/BusinessException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/NotFoundEntityException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/dto/ExceptionModel.java
Exception Handler 추가 및 Optional 적용
> Feat_Back/Exception_Handle

- front/src/components/Main.js
- front/src/components/common/Function.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/comp/MySurveyComp.js
반복되는 함수 사용으로 인해.. 클립보드 함수를 common에 작성했습니다
> Feat_Front/ClipboardFunction [ADD ClipboardFunction]

- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
> Feat_Front/SubmitSurvey_validation [ADD all required ]

- back/src/main/java/com/mongoosereum/dou_survey_zone/DouSurveyZoneApplication.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/user/UserService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/user/SignInRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/config/RedisDBConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/JwtAuthenticationFilter.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/TokenProvider.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/test.java
토큰 저장 (cookie)
레디스를 이용한 로그아웃
임시 패스워드 메일 전송
> Feat_Back/addsearchPWandloginredis

- front/src/components/common/Function.js
- front/src/components/survey/UI/MySurvey.js
내 설문지 페이지에 작성한 설문이 하나도 없을시 이미지 출력
> Feat_Front/mySurvey_img

- front/src/components/Main.js
- front/src/components/MainComp.js
메인 설문 목록에 태그 추가 (오른쪽 정렬 적용 못함)
> Feat_Front/MainSurveyList_tag [ADD tag in SurveyList]

- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/comp/MySurveyComp.js
내 설문페이지에서
- 설문 상태에 따른 진행전,중,마감 표기
- 설문 삭제 시, 리스트 업데이트
> Feat_Front/MySurvey_surveyState [ADD state flag of survey & update surveyList after delete]

- front/src/components/common/UI/ReqSwitch.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
설문 생성
1. 공개 설문인지 비공개 설문인지 사용자에게 보여주도록 수정
2. 해당 질문이 필수응답 항목인지 아닌지 생성시 알기 쉽도록 수정
> Fix_Front/Switch [Add ReqSwitch.js]

- front/src/components/Main.js
메인 페이지
설문지의 현재 상태[진행 전, 진행 중, 마감]의 상태에 따라 참여 버튼 생성 및 삭제 구현
> Fix_Front/attendButton

- front/src/components/find/UI/FindID.js
- front/src/components/find/UI/FindPW.js
- front/src/components/find/comp/FindIDComp.js
- front/src/components/find/comp/FindPWComp.js
- front/src/lib/api/auth.js
ID찾기 및 PW찾기 구현 [요청 데이터 폼 완성]
향후 백앤드 구현완료 되면 업데이트 필요
> Feat_Front/FindID_PW

- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
스위치 on/off 시  삭제 버튼과 함께 움직이는것 수정
> Fix_Front/ReqSwitch[css]

- front/package.json
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/SurveySubmitComp.js
설문 참여 제출 & 설문 수정 제출 시, api 요청 부분 수정
> Fix_Front/SubmitSurvey_v2 [modify submit after attend & update]

- back/pom.xml
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/SurveyDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/AuthorizationException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/BusinessException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/NotFoundEntityException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_401_Unauthorized/HasNotPermissionException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_403_Forbidden/AlreadyParticipatedException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_404_NotFound/NotFoundEntityException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/dto/ExceptionModel.java
- back/src/main/resources/mappers/survey.xml
Exception Handle v2
Enum ErrorCode 추가
> Feat_Back/Exception_HandleV2

- front/src/components/result/UI/Result.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- front/src/pages/ResultPage.js
> Feat_Front/resultPage_v1

- front/src/components/survey/comp/LinearMagnificationComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/modules/submitReducer.js
설문 생성 제출 양식 수정 
(payload 형식을 배열에서 객체로 수정)
> Fix_Front/CreateSurvey_form [modify submit form]

- front/src/components/register/UI/Register.js
- front/src/components/register/comp/RegisterComp.js
> Fix_Front/Register_Form

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/SelectSurveyRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/SurveyResultRes.java
> HotFix_Back/SelectList

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/paging/PageCriteria.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/user/UserService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/CheckEmailReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/SearchIDReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/SearchPWReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/SignUpReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/SigninReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_400_BadRequest/AlreadyRegisteredEmailException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_401_Unauthorized/HasNotPermissionException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_404_NotFound/NotFoundUserException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/TokenProvider.java
- back/src/main/resources/mappers/user.xml
> Feat_back/userExceptionV1

- front/src/components/result/UI/ResultSubjective.js
- front/src/components/result/comp/ResultComp.js
> Feat_Front/ResultSubjective

- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/comp/ResultLinearComp.js
- front/src/components/survey/comp/LinearMagnificationComp.js
결과보기 페이지
선형배율 질문에 대한 답변 출력 구현 (객관식은 틀만 구현)
> Feat_Front/ResultSurvey_v1 [ADD Linear & Multi]

- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/UI/ResultSubjective.js
설문 결과 페이지
결과 구현 [모든 문항 charts 구현 예정]
> Feat_Front/ResultSurvey_v2 [ADD Multi]

- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/charts/BarChart.js
- front/src/components/result/comp/ResultLinearComp.js
> Feat_Front/BarChart [ADD barChart]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/Answer.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/Question.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/Select.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/AuthenticationException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/AuthorizationException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/BusinessException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/NotFoundException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_403_Forbidden/NotOwnerException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/_404_NotFound/NotFoundEntityException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/dto/ExceptionModel.java
- back/src/main/resources/mappers/user.xml
> Fix_Back/SurveyException

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/TagDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ForbiddenException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/UnauthorizedException.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exceptionHandler/dto/ExceptionModel.java
> Refactor_Back/Optional

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/lib/api/home.js
- front/src/pages/MainPage.js
메인페이지의 페이징 처리 오류 수정 완료! ( 화살표 버튼 누르면 error발생했었음 )
> Fix front/paging

- front/src/components/result/charts/BarChart.js
- front/src/components/survey/UI/MainSurvey.js
BarChart 구현을 위한 data 자료형 수정 완료.
> Feat_Front/BarChart_v2 [ADD barChart]

- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/UI/ResultSubjective.js
- front/src/components/result/charts/DoughnutChart.js
> Feat_Front/DoughnutChart [ADD doughnutChart]

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/survey/UI/MySurvey.js
> Fix_Front/Paging_v2 [modify mySurvey paging]

- front/src/components/Main.js
- front/src/components/MainComp.js
메인페이지
- 태그 : 토글로 수정
- 페이징 : 홈 버튼 클릭 시, 페이지 번호 1로 초기화
> Fix_Front/Main_TagAndPaging [modify tag & paging]

- front/src/components/result/charts/LineChart.js
> Feat_Front/LineChart [ADD LineChart]

- front/src/components/result/ToggleBtn.js
- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/charts/BarChart.js
- front/src/components/result/charts/DoughnutChart.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/result/comp/ResultLinearComp.js
- front/src/components/result/comp/ResultMultiComp.js
선 차트, 도넛 차트, 바 차트를 토글 버튼에 따라 출력
> Feat_Front/ChartToggleBtn

- front/src/components/result/ToggleBtn.js
> Feat_Front/ChartToggleBtn v2

- front/src/components/common/UI/Header.js
- front/src/components/login/comp/LoginComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/lib/api/auth.js
기존 user_Token 쿠키 Authorization로 변경
> Fix_Front/Cookie [modify cookie to Authorization]

- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/MainSurvey.js
- 설문 생성 시, 태그 선택 안함 추가
- 태그 선택 없을 시, 별도 처리
> Fix_Front/Survey_tag [modify no check tag]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/TagDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/TagDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/survey/Survey_MySQL.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/tag/SurveyTag.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
- back/src/main/resources/mappers/tag.xml
> Fix_Back/SurveyUpdate

- front/package.json
- front/src/components/result/UI/Result.js
> Fix_Front/ResultSurvey_CSS [Add Css]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/TagDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/TagDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/user/SignInRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ExceptionHandlerController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ExceptionModel.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/UserService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/TokenProvider.java
- back/src/main/resources/mappers/participation.xml
- back/src/main/resources/mappers/tag.xml
- back/src/main/resources/mappers/user.xml
> Fix_Back/SearchPW

- front/src/components/common/UI/ErrorSweet.js
- front/src/components/register/comp/RegisterComp.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/charts/DoughnutChart.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/result/comp/ResultLinearComp.js
- front/src/components/result/comp/ResultMultiComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/lib/api/home.js
> Feat_Front/ErrorCode [ADD handle error code]

- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/lib/api/survey.js
- 설문에 참여한 IP block 처리
- 진행 전 설문 참여에 대한 block 처리
> Feat_Front/overlapIP [ADD process overlapIP]

- front/src/components/register/UI/Register.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/MultipleChoiceComp.js
기존 설문지 상태에 따른 disabled를 ReadOnly로 수정
> Fix_Front/disabled_ReadOnly

- front/src/App.js
- front/src/components/find/UI/ChangePW.js
- front/src/components/find/UI/FindID.js
- front/src/components/find/UI/FindPW.js
- front/src/components/find/comp/ChangePWComp.js
- front/src/components/find/comp/FindIDComp.js
- front/src/components/find/comp/FindPWComp.js
- front/src/components/login/comp/LoginComp.js
- front/src/pages/ChangePWPage.js
ID/PW 찾기 처리 구현 (임시 비밀번호로 로그인 시, 비밀번호 변경 처리 미구현)
> Feat_Front/Find_IDPW [ADD complete find id & pw]

- front/src/components/common/Function.js
UI 구성 시 편리하게 공백 처리를 하기 위한 함수 작성
> Feat_Front/Gongback_Function

- front/src/components/common/UI/OTL.js
- front/src/components/result/UI/Result.js
- front/src/components/survey/UI/MySurvey.js
내 설문 페이지 접근 시 생성한 설문이 하나도 없거나
결과 보기 페이지 접근 시 응답이 하나도 없을 경우 보여질 View 작성
> Feat_Front/NullView_OTL

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/resources/templates/resetPW.html
- back/src/main/resources/templates/surveyEndMail.html
- back/src/main/resources/templates/surveyStartMail.html
> Refect_Back/html

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/UserDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/user/ChagePWReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/UserService.java
- back/src/main/resources/mappers/user.xml
> Feat_back/S3 UPload

- front/src/App.js
- front/src/components/common/UI/Header.js
- front/src/components/find/comp/ChangePWComp.js
- front/src/components/login/comp/LoginComp.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/SurveySubmitComp.js
- front/src/pages/ChangePWPage.js
- front/src/pages/CreateSurveyPage.js
- front/src/pages/FindIDPage.js
- front/src/pages/FindPWPage.js
- front/src/pages/LoginPage.js
- front/src/pages/MainPage.js
- front/src/pages/MySurveyPage.js
- front/src/pages/ReadOnlyPage.js
- front/src/pages/RegisterPage.js
- front/src/pages/ResultPage.js
- front/src/pages/SurveySubmitPage.js
- front/src/pages/UpdatePage.js
page에 header, footer 다시 되돌림 (rendering 문제로 인하여)
> Fix_Front/Page_fixBar [modify page]

- front/src/components/survey/comp/CreateSurveyComp.js
> Fix_Fornt/Image_v2

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/TestController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/SendSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/UserService.java
- back/src/main/resources/templates/sendSurveyMail.html
> Feat_Back/SendSurveybyEmail

- front/src/components/common/UI/Header.js
- front/src/components/common/UI/OTL.js
- front/src/components/result/UI/Result.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/comp/CreateSurveyComp.js
> Feat_Front/Image [ADD image to Survey]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/SendSurveyReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
> Fix_Back/InsertSurvey_NoImage

- front/src/components/survey/UI/EList.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/SendEmail.js
- front/src/lib/api/survey.js
내 설문 페이지에서 전송할 이메일을 작성한뒤 전송하도록 구현
> Feat_Front/SendEmail

- front/src/App.js
- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/common/Function.js
- front/src/components/find/UI/ChangePW.js
- front/src/components/find/UI/FindID.js
- front/src/components/find/UI/FindPW.js
- front/src/components/login/UI/Login.js
- front/src/components/register/UI/Register.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/SurveySubmit.js
> Feat_Front/DarkMode [ADD dark mode]

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/survey/UI/SendEmail.js
> Fix_Front/Main_render [modify main render optimization]

- front/package.json
- front/src/App.js
- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/common/UI/FullImageCard.js
- front/src/components/common/UI/Header.js
- front/src/components/common/UI/SurveyDialog.js
- front/src/components/common/UI/TagColor.js
- front/src/components/result/charts/MyResponsiveLine.js
- front/src/components/result/charts/MyResponsivePie.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/modules/chartReducer.js
- front/yarn.lock
- Main 컴포넌트 및 UI 수정
- Header UI 수정
- BackGroundColor 색상 변경
> Feat_Front/UI [Modify UI to Main & Header ]

- front/package.json
- front/src/components/common/Function.js
- front/src/components/common/UI/ReqSwitch.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/SendEmail.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/CreateSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/SubjectiveComp.js
- front/yarn.lock
> Fix_Front/UI [Modify UI to Suvey ]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/common/MainInfoRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/ParticipationService.java
- back/src/main/resources/mappers/participation.xml
- back/src/main/resources/mappers/survey.xml
> Refect_back/suverytotalacc

- front/src/components/common/UI/ReqSwitch.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/CreateSurveyComp.js
전반적인 css 수정과 merge 이후, 재수정
(내 설문지-수정 부분 css 수정 필요)
> Fix_Front/UpdateSurvey_re-edit [modify after merge]

- front/package.json
- front/src/components/Main.js
- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/UI/ResultSubjective.js
- front/src/components/survey/UI/BeforeSurvey.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/UI/SurveySubmit.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/yarn.lock
> Feat_Front/UI [Modify Fianl UI]

- front/package.json
- front/src/components/common/debounceFunction.js
- front/src/components/register/comp/RegisterComp.js
- front/src/components/result/charts/MyResponsiveLine.js
- front/src/components/survey/comp/MySurveyCalendar.js
- front/src/lib/api/survey.ts
- front/yarn.lock
Enter Key 남발 및 광클에 의한 무분별한 API요청 방지
> Refactor_Front/BigBang_v2.1

- front/package.json
- front/src/components/Main.js
- front/src/components/common/modules/Header.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/comp/CreateSurveyComp.tsx
- front/src/components/survey/comp/SurveySubmitComp.tsx
> Fix_Front/smallbang_v1

- front/package.json
- front/src/App.js
- front/src/components/common/Function.js
- front/src/components/result/UI/Result.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/survey/UI/CreateSurvey.js
- front/src/components/survey/UI/LinearMagnification.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/UI/MultipleChoice.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/QrCodeUrl.js
- front/src/components/survey/UI/SendEmail.js
- front/src/components/survey/UI/Subjective.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/yarn.lock
- 내 설문 페이지 QR 코드 생성 추가 및 QR 코드 다운로드 기능 완료
- 설문지 CSS 수정
> Feat_Front/QRcode [ ADD QRcode & Modify CSS to Survey ]

- front/src/components/common/modules/SurveyDialog.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/comp/ResultLinearComp.js
- front/src/components/result/comp/ResultMultiComp.js
결과 보기 페이지에 질문 항목마다 성비 및 연령대의 결과물을 볼수있도록 제작 중.
> Feat_Front/DetailResultChart_v1

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/result/UI/ResultSubjective.js
- front/src/components/survey/comp/SurveySubmitComp.tsx
설문 댓글 달기 front CRUD 완성 [ API 미완성 ]
> Feat_Front/Comment_v1 [ ADD comment to survey ]

- back/pom.xml
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/mail/MailService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/CommonController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/UserController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/CommentDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/CommentDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/ParticipationDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/domain/comment/Comment.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/DeleteCommentReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/InsertCommentReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/CommentListRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/SurveyResultRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/exception/ErrorCode.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/config/MySQLDBConfig.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/security/test.java
- back/src/main/resources/mappers/participation.xml
- back/src/main/resources/templates/sendSurveyMail.html
> Feat_Back/SurveyComment

- front/src/components/MainComp.js
- front/src/components/common/debounceFunction.js
- front/src/components/common/modules/SurveyDialog.js
- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultDetailChart.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/UI/ResultSubjective.js
- front/src/components/result/charts/MyResponsiveLine.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/result/comp/ResultLinearComp.js
- front/src/components/result/comp/ResultMultiComp.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/MySurveyCalendar.js
진웅 - 메인페이지 댓글 modal 로 변경 및 수정 구현 (API 미완성)
유나 - 결과 페이지 세부 결과 차트 구현 (API 미완성)
> Feat_Front/Comment & Result [ ADD detail Result chart ]

- front/src/components/Main.js
- front/src/components/MainComp.js
- front/src/components/common/debounceFunction.js
- front/src/components/login/UI/Login.js
- front/src/components/result/ToggleBtn.js
- front/src/components/result/UI/Result.js
- front/src/components/result/UI/ResultLinear.js
- front/src/components/result/UI/ResultMulti.js
- front/src/components/result/charts/MyResponsivePie.js
- front/src/components/result/comp/ResultComp.js
- front/src/components/survey/UI/MySurvey.js
- front/src/components/survey/UI/QrCodeUrl.js
- front/src/components/survey/comp/CreateSurveyComp.tsx
- front/src/components/survey/comp/MultipleChoiceComp.js
- front/src/components/survey/comp/MySurveyComp.js
- front/src/components/survey/comp/SurveySubmitComp.tsx
- front/src/lib/api/survey.ts
- 진웅 : 댓글 CRUD 구현
- 유나 : 결과 페이지 상세 그래프 데이터 가공
> Feat_Front/Comment & Result v2 [ ADD update & delete to comment ]

- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/common/paging/PageCriteria.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/controller/SurveyController.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/CommentDAO.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dao/CommentDAOImpl.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/request/survey/CommentListPageReq.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/CommentListRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/dto/response/survey/SurveyResultRes.java
- back/src/main/java/com/mongoosereum/dou_survey_zone/api/v1/service/SurveyService.java
- back/src/main/resources/mappers/comment.xml
- back/src/main/resources/mappers/tag.xml
> Feat_Back/commentpagenation

- front/package.json
- front/src/App.js
- front/src/components/comment/Comment.js
- front/src/components/comment/DelComment.js
- front/src/components/comment/ModifyComment.js
- front/src/components/common/modules/NotFound.js
- front/src/components/login/UI/Login.js
- front/src/components/survey/UI/MainSurvey.js
- front/src/components/survey/comp/MainSurveyComp.js
- front/src/lib/api/survey.ts
- front/src/pages/NotFoundPage.js
> Feat_Front/Comment_pagination [ ADD paging to Comment ]
